<?php

namespace MarsGameBundle\Repository;

/**
 * CityResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityResourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
