<?php

namespace MarsGameBundle\Repository;

/**
 * CityBuildingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityBuildingsRepository extends \Doctrine\ORM\EntityRepository
{
}
